---
title: "9_4 Probability"
output: html_notebook
---


```{r}
set.seed(987432) # used to anchor the random number generator; will produce same random number so code is reproducible
library(dplyr)

N <- 1000
pet <- sample(c("dog", "cat"), N, replace = TRUE)
p <- .2*(pet=="dog") + .4
favorite_color <- c("red","green")[1+rbinom(N,1,p)]
df <- data.frame(
  pet = pet
  , color = favorite_color
)
df
```

```{r}
# estimate of the probability that someone prefers dogs for size 1,000
mean(df$pet == 'dog')

# dplyr uses pull, pull will pull column out (T/F vector) to be evaluated
df %>% 
  mutate(dog = 1*(pet=='dog')) %>% 
  pull(dog) %>% 
  mean()
df

df %>%
  mutate(dog_green = (pet =='dog' & color == 'green')) %>% 
           pull(dog_green) %>% 
           mean()
df

# difference between select and pull = select --> df, pull --> vector
df %>%
  mutate(dog_green = (pet =='dog' & color == 'green')) %>% 
           select(dog_green) 

df_dog<- with(df,(pet=='dog' & color == 'green'))
df_dog

# calc mean of person whose fav color is red given they like dog
df %>% filter(pet =='dog') %>% summarize(p = mean(color=='red'))

df$dog_green <- NULL
head(df)

require(data.table)
dt<- as.data.table(df)
head(dt)
dt[color == 'red',.N, pet]
dt[,as.list(table(pet)), color]

(312+208) / N
```


